export const Typography = {
  fontFamily: {
    regular: 'System',
    medium: 'System',
    semibold: 'System',
    bold: 'System',
    mono: 'Menlo',
  },
  fontSize: {
    xs: 11,
    sm: 13,
    md: 15,
    lg: 17,
    xl: 20,
    xxl: 24,
    xxxl: 28,
    huge: 32,
    massive: 36,
    giant: 40,
    display: 48,
  },
  lineHeight: {
    tight: 1.2,
    normal: 1.4,
    relaxed: 1.6,
    loose: 1.8,
  },
  letterSpacing: {
    tight: -0.5,
    normal: 0,
    wide: 0.5,
    wider: 1,
  },
  fontWeight: {
    regular: '400' as const,
    medium: '500' as const,
    semibold: '600' as const,
    bold: '700' as const,
  },
};

export const TextStyles = {
  display: {
    fontSize: Typography.fontSize.display,
    fontWeight: Typography.fontWeight.bold,
    lineHeight: Typography.fontSize.display * Typography.lineHeight.tight,
    letterSpacing: Typography.letterSpacing.tight,
  },
  h1: {
    fontSize: Typography.fontSize.giant,
    fontWeight: Typography.fontWeight.bold,
    lineHeight: Typography.fontSize.giant * Typography.lineHeight.tight,
    letterSpacing: Typography.letterSpacing.tight,
  },
  h2: {
    fontSize: Typography.fontSize.massive,
    fontWeight: Typography.fontWeight.bold,
    lineHeight: Typography.fontSize.massive * Typography.lineHeight.tight,
    letterSpacing: Typography.letterSpacing.tight,
  },
  h3: {
    fontSize: Typography.fontSize.huge,
    fontWeight: Typography.fontWeight.semibold,
    lineHeight: Typography.fontSize.huge * Typography.lineHeight.normal,
    letterSpacing: Typography.letterSpacing.normal,
  },
  h4: {
    fontSize: Typography.fontSize.xxxl,
    fontWeight: Typography.fontWeight.semibold,
    lineHeight: Typography.fontSize.xxxl * Typography.lineHeight.normal,
    letterSpacing: Typography.letterSpacing.normal,
  },
  h5: {
    fontSize: Typography.fontSize.xxl,
    fontWeight: Typography.fontWeight.semibold,
    lineHeight: Typography.fontSize.xxl * Typography.lineHeight.normal,
    letterSpacing: Typography.letterSpacing.normal,
  },
  h6: {
    fontSize: Typography.fontSize.xl,
    fontWeight: Typography.fontWeight.medium,
    lineHeight: Typography.fontSize.xl * Typography.lineHeight.normal,
    letterSpacing: Typography.letterSpacing.normal,
  },
  bodyLarge: {
    fontSize: Typography.fontSize.lg,
    fontWeight: Typography.fontWeight.regular,
    lineHeight: Typography.fontSize.lg * Typography.lineHeight.relaxed,
    letterSpacing: Typography.letterSpacing.normal,
  },
  body: {
    fontSize: Typography.fontSize.md,
    fontWeight: Typography.fontWeight.regular,
    lineHeight: Typography.fontSize.md * Typography.lineHeight.relaxed,
    letterSpacing: Typography.letterSpacing.normal,
  },
  bodySmall: {
    fontSize: Typography.fontSize.sm,
    fontWeight: Typography.fontWeight.regular,
    lineHeight: Typography.fontSize.sm * Typography.lineHeight.relaxed,
    letterSpacing: Typography.letterSpacing.normal,
  },
  caption: {
    fontSize: Typography.fontSize.xs,
    fontWeight: Typography.fontWeight.regular,
    lineHeight: Typography.fontSize.xs * Typography.lineHeight.normal,
    letterSpacing: Typography.letterSpacing.wide,
  },
  overline: {
    fontSize: Typography.fontSize.xs,
    fontWeight: Typography.fontWeight.medium,
    lineHeight: Typography.fontSize.xs * Typography.lineHeight.normal,
    letterSpacing: Typography.letterSpacing.wider,
    textTransform: 'uppercase' as const,
  },
  button: {
    fontSize: Typography.fontSize.md,
    fontWeight: Typography.fontWeight.semibold,
    lineHeight: Typography.fontSize.md * Typography.lineHeight.normal,
    letterSpacing: Typography.letterSpacing.normal,
  },
  buttonLarge: {
    fontSize: Typography.fontSize.lg,
    fontWeight: Typography.fontWeight.semibold,
    lineHeight: Typography.fontSize.lg * Typography.lineHeight.normal,
    letterSpacing: Typography.letterSpacing.normal,
  },
  link: {
    fontSize: Typography.fontSize.md,
    fontWeight: Typography.fontWeight.medium,
    lineHeight: Typography.fontSize.md * Typography.lineHeight.normal,
    letterSpacing: Typography.letterSpacing.normal,
    textDecorationLine: 'underline' as const,
  },
};