import React from 'react';
import { KeyboardAvoidingView, Platform, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { TabBar } from '@/components/ui';
import { askOria } from '@/services/ai';
import { discoverPlaces } from '@/services/places';
import { Place } from '@/core/types';
import { theme } from '@/core/theme';
type Message = { role: 'user' | 'assistant'; text: string };
const berlin = { latitude: 52.52, longitude: 13.405 };
export default function AI() { const [messages, setMessages] = React.useState<Message[]>([]); const [input, setInput] = React.useState(''); const [places, setPlaces] = React.useState<Place[]>([]); const [waiting, setWaiting] = React.useState(false); React.useEffect(() => { discoverPlaces(berlin).then(setPlaces).catch(() => undefined); }, []); const send = async (suggestion?: string) => { const question = suggestion || input.trim(); if (!question || waiting) return; setInput(''); setMessages((all) => [...all, { role: 'user', text: question }]); setWaiting(true); try { const answer = await askOria(question, places); setMessages((all) => [...all, { role: 'assistant', text: answer }]); } catch (error: any) { setMessages((all) => [...all, { role: 'assistant', text: error.message || 'Das hat gerade nicht geklappt.' }]); } finally { setWaiting(false); } }; return <SafeAreaView style={styles.page}><KeyboardAvoidingView style={styles.fill} behavior={Platform.select({ ios: 'padding', default: undefined })}><View style={styles.header}><Text style={styles.title}>Oria AI</Text><Text style={styles.subtitle}>Ein eigener Raum für Ideen, nicht deine Karte.</Text></View><ScrollView contentContainerStyle={styles.thread}>{messages.length === 0 ? <><Text style={styles.intro}>Worauf hast du heute Lust?</Text><View style={styles.prompts}>{['Ein ruhiges Café zum Arbeiten', 'Ein Spaziergang mit gutem Kaffee', 'Etwas Kulturelles für heute Abend'].map((prompt) => <TouchableOpacity key={prompt} onPress={() => send(prompt)} style={styles.prompt}><Text style={styles.promptText}>{prompt}</Text></TouchableOpacity>)}</View></> : messages.map((message, index) => <View key={index} style={[styles.message, message.role === 'user' ? styles.user : styles.assistant]}><Text style={[styles.messageText, message.role === 'user' && styles.userText]}>{message.text}</Text></View>)}{waiting && <Text style={styles.thinking}>Oria denkt nach …</Text>}</ScrollView><View style={styles.composer}><TextInput value={input} onChangeText={setInput} onSubmitEditing={() => send()} placeholder="Frag Oria nach Ideen" placeholderTextColor={theme.colors.muted} style={styles.input} multiline /><TouchableOpacity onPress={() => send()} style={styles.send}><Text style={styles.sendText}>↑</Text></TouchableOpacity></View></KeyboardAvoidingView><TabBar /></SafeAreaView>; }
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: theme.colors.paper }, fill: { flex: 1 }, header: { padding: 24, paddingTop: 28, borderBottomWidth: 1, borderColor: theme.colors.line, gap: 4 }, title: { color: theme.colors.ink, fontFamily: theme.fonts.black, fontSize: 34, fontWeight: '800' }, subtitle: { color: theme.colors.muted, fontFamily: theme.fonts.regular, fontSize: 14 }, thread: { padding: 20, gap: 12, flexGrow: 1 }, intro: { color: theme.colors.ink, fontFamily: theme.fonts.bold, fontSize: 24, lineHeight: 30, marginTop: 24 }, prompts: { gap: 10, marginTop: 16 }, prompt: { padding: 16, borderRadius: 12, borderWidth: 1, borderColor: theme.colors.line, backgroundColor: theme.colors.surface }, promptText: { color: theme.colors.ink, fontFamily: theme.fonts.medium, fontSize: 15 }, message: { maxWidth: '88%', padding: 14, borderRadius: 14 }, user: { alignSelf: 'flex-end', backgroundColor: theme.colors.moss }, assistant: { alignSelf: 'flex-start', backgroundColor: theme.colors.surface, borderWidth: 1, borderColor: theme.colors.line }, messageText: { color: theme.colors.ink, fontFamily: theme.fonts.regular, lineHeight: 22 }, userText: { color: theme.colors.night }, thinking: { color: theme.colors.muted, fontFamily: theme.fonts.regular, padding: 8 }, composer: { flexDirection: 'row', alignItems: 'flex-end', padding: 14, gap: 10, borderTopWidth: 1, borderColor: theme.colors.line, backgroundColor: theme.colors.surface }, input: { flex: 1, maxHeight: 110, fontFamily: theme.fonts.regular, color: theme.colors.ink, fontSize: 15, padding: 10 }, send: { width: 42, height: 42, borderRadius: 21, backgroundColor: theme.colors.moss, alignItems: 'center', justifyContent: 'center' }, sendText: { color: theme.colors.night, fontSize: 22, fontWeight: '700' } });
