import React from 'react';
import * as Location from 'expo-location';
import { ActivityIndicator, SafeAreaView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useRouter } from 'expo-router';
import { MapCanvas } from '@/components/map';
import { TabBar } from '@/components/ui';
import { Coordinates, Place } from '@/core/types';
import { theme } from '@/core/theme';
import { discoverPlaces } from '@/services/places';
import { useAppState } from '@/core/state';

const fallback = { latitude: 52.52, longitude: 13.405 };
export default function Explore() {
  const router = useRouter(); const { addSaved, saved } = useAppState();
  const [center, setCenter] = React.useState<Coordinates>(fallback); const [places, setPlaces] = React.useState<Place[]>([]); const [selected, setSelected] = React.useState<Place | null>(null); const [loading, setLoading] = React.useState(true);
  const load = React.useCallback(async (at: Coordinates) => { setLoading(true); try { setPlaces(await discoverPlaces(at)); } catch { setPlaces([]); } finally { setLoading(false); } }, []);
  React.useEffect(() => { (async () => { const permission = await Location.requestForegroundPermissionsAsync(); const current = permission.status === 'granted' ? await Location.getCurrentPositionAsync({}) : null; const at = current ? { latitude: current.coords.latitude, longitude: current.coords.longitude } : fallback; setCenter(at); load(at); })(); }, [load]);
  return <SafeAreaView style={styles.page}><View style={styles.map}><MapCanvas places={places} onSelect={setSelected} /><View style={styles.top}><Text style={styles.wordmark}>Oria</Text><TouchableOpacity onPress={() => router.push('/explore/search')} style={styles.search}><Text style={styles.searchText}>⌕  Orte suchen</Text></TouchableOpacity></View>{loading && <View style={styles.loading}><ActivityIndicator color={theme.colors.moss} /></View>}</View>{selected ? <View style={styles.sheet}><Text style={styles.placeIcon}>{selected.icon}</Text><View style={styles.sheetText}><Text style={styles.placeName}>{selected.name}</Text><Text style={styles.placeMeta}>{selected.category}{selected.distance ? ` · ${selected.distance} m` : ''}</Text><Text style={styles.address}>{selected.address || 'Ort in deiner Nähe'}</Text></View><TouchableOpacity onPress={() => addSaved(selected)} style={[styles.save, saved.some((place) => place.id === selected.id) && styles.saved]}><Text style={styles.saveText}>{saved.some((place) => place.id === selected.id) ? 'Gespeichert' : 'Merken'}</Text></TouchableOpacity></View> : <View style={styles.hint}><Text style={styles.hintText}>{places.length ? `${places.length} Orte in der Nähe` : 'Standort aktivieren, um Orte zu sehen'}</Text></View>}<TabBar /></SafeAreaView>;
}
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: theme.colors.paper }, map: { flex: 1 }, top: { position: 'absolute', top: 12, left: 16, right: 16, flexDirection: 'row', alignItems: 'center', gap: 14 }, wordmark: { color: theme.colors.ink, fontFamily: 'AlbertSans', fontWeight: '800', fontSize: 28 }, search: { flex: 1, backgroundColor: theme.colors.surface, borderRadius: 12, paddingHorizontal: 14, paddingVertical: 13, borderWidth: 1, borderColor: theme.colors.line }, searchText: { color: theme.colors.muted, fontFamily: 'Almarai' }, loading: { position: 'absolute', top: 78, right: 20, padding: 10, borderRadius: 99, backgroundColor: theme.colors.surface }, sheet: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 18, backgroundColor: theme.colors.surface, borderTopWidth: 1, borderColor: theme.colors.line }, placeIcon: { width: 38, height: 38, borderRadius: 19, backgroundColor: theme.colors.signalSoft, textAlign: 'center', lineHeight: 38 }, sheetText: { flex: 1, gap: 2 }, placeName: { color: theme.colors.ink, fontFamily: 'Almarai', fontSize: 16, fontWeight: '700' }, placeMeta: { color: theme.colors.moss, fontFamily: 'Almarai', fontSize: 13 }, address: { color: theme.colors.muted, fontFamily: 'Almarai', fontSize: 12 }, save: { borderWidth: 1, borderColor: theme.colors.moss, borderRadius: 10, padding: 10 }, saved: { backgroundColor: theme.colors.moss }, saveText: { color: theme.colors.moss, fontFamily: 'Almarai', fontWeight: '700', fontSize: 12 }, hint: { paddingHorizontal: 18, paddingVertical: 14, backgroundColor: theme.colors.surface, borderTopWidth: 1, borderColor: theme.colors.line }, hintText: { color: theme.colors.muted, fontFamily: 'Almarai', fontSize: 13 } });
