import React from 'react';
import { ActivityIndicator, FlatList, SafeAreaView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useRouter } from 'expo-router';
import { Place } from '@/core/types';
import { discoverPlaces } from '@/services/places';
import { theme } from '@/core/theme';
const berlin = { latitude: 52.52, longitude: 13.405 };
export default function Search() { const router = useRouter(); const [query, setQuery] = React.useState(''); const [items, setItems] = React.useState<Place[]>([]); const [loading, setLoading] = React.useState(false); const search = async () => { if (!query.trim()) return; setLoading(true); try { setItems(await discoverPlaces(berlin, query)); } finally { setLoading(false); } }; return <SafeAreaView style={styles.page}><View style={styles.header}><TouchableOpacity onPress={() => router.back()}><Text style={styles.back}>‹</Text></TouchableOpacity><TextInput autoFocus value={query} onChangeText={setQuery} onSubmitEditing={search} placeholder="Wen oder was suchst du?" placeholderTextColor={theme.colors.muted} style={styles.input} /></View>{loading ? <ActivityIndicator color={theme.colors.moss} style={styles.loader} /> : <FlatList data={items} keyExtractor={(item) => item.id} ListEmptyComponent={<Text style={styles.empty}>{query ? 'Keine passenden Orte gefunden.' : 'Suche nach Café, Park, Museum oder einem bestimmten Ort.'}</Text>} renderItem={({ item }) => <TouchableOpacity onPress={() => router.replace('/explore')} style={styles.row}><Text style={styles.icon}>{item.icon}</Text><View style={styles.copy}><Text style={styles.name}>{item.name}</Text><Text style={styles.meta}>{item.category}{item.distance ? ` · ${item.distance} m` : ''}</Text></View></TouchableOpacity>} />}</SafeAreaView>; }
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: theme.colors.paper, padding: 18 }, header: { flexDirection: 'row', gap: 12, alignItems: 'center', marginBottom: 20 }, back: { color: theme.colors.ink, fontSize: 40, lineHeight: 40 }, input: { flex: 1, color: theme.colors.ink, fontFamily: 'Almarai', fontSize: 16, backgroundColor: theme.colors.surface, borderWidth: 1, borderColor: theme.colors.line, borderRadius: 12, paddingHorizontal: 14, paddingVertical: 13 }, loader: { marginTop: 50 }, empty: { color: theme.colors.muted, fontFamily: 'Almarai', textAlign: 'center', marginTop: 60, lineHeight: 24 }, row: { flexDirection: 'row', gap: 14, paddingVertical: 15, borderBottomWidth: 1, borderColor: theme.colors.line }, icon: { width: 38, height: 38, borderRadius: 19, backgroundColor: theme.colors.signalSoft, textAlign: 'center', lineHeight: 38 }, copy: { gap: 3, flex: 1 }, name: { color: theme.colors.ink, fontFamily: 'Almarai', fontWeight: '700' }, meta: { color: theme.colors.muted, fontFamily: 'Almarai', fontSize: 13 } });
